### ISSUE TITLE
Callback function should return true.

### ISSUE THREAD

**Issue by vivekimsit** [dominictarr/libnested#1]
Many people consider undefined == false, and not undefined !== false, it would be better to remove the ambiguity and return `true` when expected condition is met, wdyt?

**Comment by dominictarr** [comment]
sure, it doesn't really matter what you return. I guess I could have made it true, but since it's a negative action - that is, it stops, I'd rather have it run until it returns true, but I just wanted it to default to true.

Remember, this is a special case, I don't want to have to always return true.

**Comment by dominictarr** [comment]
for node streams, returning `stream.write(data)===false` means pause...

**Comment by vivekimsit** [comment]
If its consistent with the node api then its fine, otherwise things are always opinionated in programming :)

I think you can close this now.
